ALTER TABLE "LoanSimulation"
  ADD COLUMN IF NOT EXISTS "usage" TEXT NOT NULL DEFAULT 'MAIN_RESIDENCE',
  ADD COLUMN IF NOT EXISTS "propertyState" TEXT NOT NULL DEFAULT 'OLD',
  ADD COLUMN IF NOT EXISTS "notaryFeesCents" INTEGER NOT NULL DEFAULT 0;
